### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'tmp/parsed.conll09'

### ISSUE THREAD

**Issue by renespeck** [UKPLab/props-de#2]
Hi, 

I installed everything and tried the example call but get an error:

```
➜  props-de git:(master) ✗ python parse_props.py -t --props --oie examples.txt
Traceback (most recent call last):
  File "parse_props.py", line 101, in <module>
    main(arguments)
  File "parse_props.py", line 45, in main
    gs = run.parseSentences(arguments["file"])
  File "/home/rspeck/test/props-de/propsde/applications/run.py", line 26, in parseSentences
    output_file = parser.parse(sentences)
  File "/home/rspeck/test/props-de/propsde/dependency_tree/german_parser.py", line 46, in parse
    parsed_conll09 = self.parse_external(sentences)
  File "/home/rspeck/test/props-de/propsde/dependency_tree/german_parser.py", line 78, in parse_external
    input = codecs.open(self.tmp+'/input.conll09', 'w', encoding='utf-8')
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'tmp/input.conll09'
```

Thanks for help.

**Comment by tbsflk** [comment]
You might need to create the 'tmp' folder manually once. Let me know if that fixes the issue.

**Comment by renespeck** [comment]
Hi, thanks for your fast response. The `temp` folder exists and has already some files.

**Comment by tbsflk** [comment]
Hm, that's weird. The line of code causing the exception is opening the file for *writing*, not reading, so even the file not being there shouldn't be an issue. It is also strange that you see files there because this is the first file being created, containing just the input.

I don't have any idea other than making sure the folder `tmp` (not `temp`) exists and the script has permission to access it.

**Comment by frederikmann** [comment]
@renespeck have you had any luck ? I have a similar issue ..
